# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import interface_pb2 as client__interface__clone_dot_interface__utils_dot_interface__pb2


class InterfaceControllerStub(object):
  """The greeting service definition.
  Sends next task to client
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.do_task = channel.unary_unary(
        '/interface.InterfaceController/do_task',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceTaskSubmit.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultResponse.FromString,
        )
    self.get_last_response = channel.unary_unary(
        '/interface.InterfaceController/get_last_response',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultRequest.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceStringResponse.FromString,
        )
    self.get_models = channel.unary_unary(
        '/interface.InterfaceController/get_models',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultRequest.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceStringResponse.FromString,
        )
    self.stop_task = channel.unary_unary(
        '/interface.InterfaceController/stop_task',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultRequest.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultResponse.FromString,
        )
    self.get_task_request = channel.unary_unary(
        '/interface.InterfaceController/get_task_request',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.TaskRequest.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.TaskResponse.FromString,
        )
    self.fetch_model_request = channel.unary_stream(
        '/interface.InterfaceController/fetch_model_request',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultRequest.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.Model.FromString,
        )
    self.train_model_response = channel.unary_unary(
        '/interface.InterfaceController/train_model_response',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultRequest.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.FromString,
        )
    self.send_model_update_response = channel.stream_unary(
        '/interface.InterfaceController/send_model_update_response',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.Model.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.FromString,
        )
    self.send_validation_loss_response = channel.unary_unary(
        '/interface.InterfaceController/send_validation_loss_response',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.Loss.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.FromString,
        )
    self.test_connection = channel.unary_unary(
        '/interface.InterfaceController/test_connection',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultRequest.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.FromString,
        )
    self.stop_response = channel.unary_unary(
        '/interface.InterfaceController/stop_response',
        request_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultRequest.SerializeToString,
        response_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.FromString,
        )


class InterfaceControllerServicer(object):
  """The greeting service definition.
  Sends next task to client
  """

  def do_task(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_last_response(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_models(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stop_task(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_task_request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def fetch_model_request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def train_model_response(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send_model_update_response(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send_validation_loss_response(self, request, context):
    """rpc fetch_test_data_response (DefaultRequest) returns (stream JsonData) {
    }

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def test_connection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stop_response(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InterfaceControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'do_task': grpc.unary_unary_rpc_method_handler(
          servicer.do_task,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceTaskSubmit.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultResponse.SerializeToString,
      ),
      'get_last_response': grpc.unary_unary_rpc_method_handler(
          servicer.get_last_response,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultRequest.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceStringResponse.SerializeToString,
      ),
      'get_models': grpc.unary_unary_rpc_method_handler(
          servicer.get_models,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultRequest.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceStringResponse.SerializeToString,
      ),
      'stop_task': grpc.unary_unary_rpc_method_handler(
          servicer.stop_task,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultRequest.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.InterfaceDefaultResponse.SerializeToString,
      ),
      'get_task_request': grpc.unary_unary_rpc_method_handler(
          servicer.get_task_request,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.TaskRequest.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.TaskResponse.SerializeToString,
      ),
      'fetch_model_request': grpc.unary_stream_rpc_method_handler(
          servicer.fetch_model_request,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultRequest.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.Model.SerializeToString,
      ),
      'train_model_response': grpc.unary_unary_rpc_method_handler(
          servicer.train_model_response,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultRequest.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.SerializeToString,
      ),
      'send_model_update_response': grpc.stream_unary_rpc_method_handler(
          servicer.send_model_update_response,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.Model.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.SerializeToString,
      ),
      'send_validation_loss_response': grpc.unary_unary_rpc_method_handler(
          servicer.send_validation_loss_response,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.Loss.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.SerializeToString,
      ),
      'test_connection': grpc.unary_unary_rpc_method_handler(
          servicer.test_connection,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultRequest.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.SerializeToString,
      ),
      'stop_response': grpc.unary_unary_rpc_method_handler(
          servicer.stop_response,
          request_deserializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultRequest.FromString,
          response_serializer=client__interface__clone_dot_interface__utils_dot_interface__pb2.DefaultResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'interface.InterfaceController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
